### ISSUE TITLE
Add a short HTTP timeout to logo request

### ISSUE THREAD

**Issue by robhanlon22** [WebReflection/lightercollective#3]
Howdy, I recently had `lightercollective postinstall` hang for a particularly long time because sometimes I have to connect to the internet through a corporate proxy. What do you say to having a really short timeout on the logo request (200 ms?) so that if it hangs it doesn't interrupt `npm install`?

**Comment by WebReflection** [comment]
Howdy, you are using an old software 'cause `lightercollective` doesn't use the network at all since 1 or 2 years ago.

I suggest you update your dependencies, specially because even to use the [latest features that let you disable completely _lightercollective_](https://github.com/WebReflection/lightercollective/blob/master/index.js#L8-L14) you need to do so.

**Comment by robhanlon22** [comment]
How about the part where it does use the network here when it calls `http.get` or `https.get`?

https://github.com/WebReflection/lightercollective/blob/master/index.js#L18

I understand that it _can_ be disabled, but it would be nice if the default behavior doesn't involve needing to look up the documentation for a library that usually isn't even directly installed.

**Comment by WebReflection** [comment]
> How about the part where it does use the network here when it calls `http.get` or `https.get`?

How [about it](https://github.com/WebReflection/lightercollective/blob/master/index.js#L17)? Not a single project of mine goes through that request, example:
https://github.com/WebReflection/hyperHTML/blob/master/package.json#L159-L163

> I understand that it _can_ be disabled, but it would be nice if the default behavior doesn't involve needing to look up the documentation for a library that usually isn't even directly installed.

It would be nice if whoever is using this library would know [how to](https://github.com/WebReflection/lightercollective#how-to) use it though.

The [how to disable](https://github.com/WebReflection/lightercollective#disabling-this-message) is there too, and by default this **project** ('cause this ain't no library) does exactly what it's meant to do: a drop in replacement for _opencollective_, which beside having exact same defaults, it has also extra 24MB on top for stuff nobody including it indirectly uses.

So, you are welcome.
